version: '3.7'
services:
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - api
  go:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        SERVER_HTTP_PORT: ${SERVER_HTTP_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api
    depends_on:
      - pg
    ports:
      - "${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}"
    tty: true
networks:
  api:
    driver: bridge
