version: '3.7'
services:
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - api
  go:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - api
    depends_on:
      - pg
    ports:
      - "8080:8080"
    tty: true
networks:
  api:
    driver: bridge
