#!/usr/bin/env bash

protoc --go_out=./music --go_opt=paths=source_relative \
  --go-grpc_out=./music --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out=./music --grpc-gateway_opt=paths=source_relative \
   --grpc-gateway_opt generate_unbound_methods=true  music.proto
